# Numpy
## Examples
* arange, linspace
* opérations
* ufunc
* methodes/ numpy functions (max, min, mean, std, sort, ...)
* Why numpy? data type

In [7]:
import numpy as np

In [8]:
l = [1, 2, 4]
l.append('COUCOU')
l

[1, 2, 4, 'COUCOU']

In [10]:
data = np.array([1, 2, 4])
data

array([1, 2, 4])

In [11]:
np.array([1, 2, 4])

array([1, 2, 4])

In [12]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [16]:
x = np.linspace(start=0, stop=1, num=10, endpoint=False)

In [18]:
y = 2*x + 1
y

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8])

In [19]:
np.sin(x)

array([0.        , 0.09983342, 0.19866933, 0.29552021, 0.38941834,
       0.47942554, 0.56464247, 0.64421769, 0.71735609, 0.78332691])

In [20]:
import math

math.sin(x)

TypeError: only size-1 arrays can be converted to Python scalars

In [23]:
logspace(1, 3)

array([  10.        ,   10.98541142,   12.06792641,   13.25711366,
         14.56348478,   15.9985872 ,   17.57510625,   19.30697729,
         21.20950888,   23.29951811,   25.59547923,   28.11768698,
         30.88843596,   33.93221772,   37.2759372 ,   40.94915062,
         44.98432669,   49.41713361,   54.28675439,   59.63623317,
         65.51285569,   71.9685673 ,   79.06043211,   86.85113738,
         95.40954763,  104.81131342,  115.13953993,  126.48552169,
        138.94954944,  152.64179672,  167.68329368,  184.20699693,
        202.35896477,  222.29964825,  244.20530945,  268.26957953,
        294.70517026,  323.74575428,  355.64803062,  390.69399371,
        429.19342601,  471.48663635,  517.94746792,  568.9866029 ,
        625.05519253,  686.648845  ,  754.31200634,  828.64277285,
        910.29817799, 1000.        ])

In [24]:
np.cos(x)

array([1.        , 0.99500417, 0.98006658, 0.95533649, 0.92106099,
       0.87758256, 0.82533561, 0.76484219, 0.69670671, 0.62160997])

In [27]:
def gaussian(x, amplitude, center, sigma):
    return amplitude * np.exp(-(x-center)**2/(2*sigma**2))

x = np.linspace(-2, 2)
gaussian(x, amplitude=1, center=.2, sigma=.5)

array([6.25215038e-05, 1.26538945e-04, 2.49369101e-04, 4.78503047e-04,
       8.94026542e-04, 1.62644640e-03, 2.88106287e-03, 4.96923290e-03,
       8.34544707e-03, 1.36468840e-02, 2.17290644e-02, 3.36877646e-02,
       5.08542200e-02, 7.47490089e-02, 1.06981213e-01, 1.49084754e-01,
       2.02293806e-01, 2.67273300e-01, 3.43836679e-01, 4.30697616e-01,
       5.25310849e-01, 6.23855359e-01, 7.21398253e-01, 8.12250338e-01,
       8.90488575e-01, 9.50583869e-01, 9.88043730e-01, 9.99966681e-01,
       9.85413551e-01, 9.45529684e-01, 8.83396030e-01, 8.03635948e-01,
       7.11847403e-01, 6.13957193e-01, 5.15600009e-01, 4.21610461e-01,
       3.35686192e-01, 2.60243094e-01, 1.96448441e-01, 1.44391490e-01,
       1.03337570e-01, 7.20109485e-02, 4.88610116e-02, 3.22812255e-02,
       2.07663998e-02, 1.30075662e-02, 7.93331169e-03, 4.71125517e-03,
       2.72422123e-03, 1.53381068e-03])

In [33]:
def scalar_my_abs(x):
    if x<0:
        return -x
    else:
        return x
    
def array_my_abs(x):
    N = len(x)
    output_array = np.zeros(N)
    for i in range(N):
        output_array[i] = scalar_my_abs(x[i])
    return output_array


In [34]:
array_my_abs(x)

array([2.        , 1.91836735, 1.83673469, 1.75510204, 1.67346939,
       1.59183673, 1.51020408, 1.42857143, 1.34693878, 1.26530612,
       1.18367347, 1.10204082, 1.02040816, 0.93877551, 0.85714286,
       0.7755102 , 0.69387755, 0.6122449 , 0.53061224, 0.44897959,
       0.36734694, 0.28571429, 0.20408163, 0.12244898, 0.04081633,
       0.04081633, 0.12244898, 0.20408163, 0.28571429, 0.36734694,
       0.44897959, 0.53061224, 0.6122449 , 0.69387755, 0.7755102 ,
       0.85714286, 0.93877551, 1.02040816, 1.10204082, 1.18367347,
       1.26530612, 1.34693878, 1.42857143, 1.51020408, 1.59183673,
       1.67346939, 1.75510204, 1.83673469, 1.91836735, 2.        ])

In [35]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a[2] = 45.85
a

array([ 0,  1, 45,  3,  4,  5,  6,  7,  8,  9])

In [42]:
a[2] = 45.85 + 2J

TypeError: can't convert complex to int

In [43]:
x = np.linspace(0, 1, 11)
y = np.linspace(0, 1, 21)

x + y

ValueError: operands could not be broadcast together with shapes (11,) (21,) 

In [44]:
np.sum(x)

5.500000000000001

In [45]:
x.sum()

5.500000000000001

In [50]:
x = np.random.rand(10000000) # between 0 and 1

print(x.min())
print(x.max())
print(x.mean())
print(x.var())
print(x.std())

8.723659072895629e-08
0.9999997803900368
0.49991615966717146
0.08330616568401443
0.28862807501006277


In [55]:
a = np.array([1, 2, 4, 1], dtype='complex')
a.dtype

dtype('complex128')

In [58]:
np.zeros(100, dtype='complex')

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

### Indexing arrays

In [59]:
x = linspace(0, 1)
x

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [61]:
x[1]

0.02040816326530612

In [63]:
x[-1] # same as x[len(X)-1] 

1.0

In [67]:
x[2:-1] # size = len(X) -1 -2 

array([0.04081633, 0.06122449, 0.08163265, 0.10204082, 0.12244898,
       0.14285714, 0.16326531, 0.18367347, 0.20408163, 0.2244898 ,
       0.24489796, 0.26530612, 0.28571429, 0.30612245, 0.32653061,
       0.34693878, 0.36734694, 0.3877551 , 0.40816327, 0.42857143,
       0.44897959, 0.46938776, 0.48979592, 0.51020408, 0.53061224,
       0.55102041, 0.57142857, 0.59183673, 0.6122449 , 0.63265306,
       0.65306122, 0.67346939, 0.69387755, 0.71428571, 0.73469388,
       0.75510204, 0.7755102 , 0.79591837, 0.81632653, 0.83673469,
       0.85714286, 0.87755102, 0.89795918, 0.91836735, 0.93877551,
       0.95918367, 0.97959184])

In [68]:
x[-1] = 3
x

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 3.        ])

In [69]:
x[2:-1] = 0.1
x

array([0.        , 0.02040816, 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.1       , 0.1       , 0.1       , 3.        ])

In [71]:
x[2:-1] = np.random.rand(len(x)-1-2)
x

array([0.        , 0.02040816, 0.55267224, 0.2941278 , 0.46719123,
       0.8904504 , 0.57837322, 0.42808793, 0.81743781, 0.94668778,
       0.71314724, 0.34649481, 0.0631918 , 0.21156901, 0.22744893,
       0.94223491, 0.56369283, 0.03294558, 0.45286479, 0.55248285,
       0.27146329, 0.32379079, 0.05907737, 0.51856013, 0.06320139,
       0.71492795, 0.22636972, 0.88448972, 0.25148067, 0.44873571,
       0.04151731, 0.66429204, 0.51343084, 0.69333545, 0.58486345,
       0.56032919, 0.48403237, 0.45860245, 0.82392492, 0.84669468,
       0.17779574, 0.28887085, 0.3019318 , 0.35962631, 0.07427112,
       0.51628763, 0.53587647, 0.62678374, 0.5545777 , 3.        ])

In [72]:
indices = np.array([1, 5, 2])
x[indices] # x[indices[j]] 

array([0.02040816, 0.8904504 , 0.55267224])

In [74]:
x = np.random.rand(10)
print(x)
k = x.argsort()
print(k)
print(x[k[0]])

[0.89975413 0.39992323 0.70029266 0.26464313 0.41646981 0.96078393
 0.09479356 0.22530424 0.6640189  0.06383345]
[9 6 7 3 1 4 8 2 0 5]
0.0638334454077617


In [75]:
print(x[k])

[0.06383345 0.09479356 0.22530424 0.26464313 0.39992323 0.41646981
 0.6640189  0.70029266 0.89975413 0.96078393]


In [76]:
linspace(start=0, stop=2, num=5)
# start + (stop-start)/(num-1)*i for i in range(num)

array([0. , 0.5, 1. , 1.5, 2. ])

In [79]:
x = np.arange(5)
mask = np.array([True, True, False, True, False])

x[mask]
x[mask] = 1
print(x)
x[mask] = np.array([6, 7, 8])
print(x)

[1 1 2 1 4]
[6 7 2 8 4]


In [82]:
x = np.random.rand(20) - .5
print(x)

x[x<0] = -x[x<0]
print(x)

[ 0.28250342  0.45662651 -0.22633228 -0.30394271 -0.0153061   0.10791063
 -0.11257571  0.27519945 -0.36548304 -0.22713978  0.33924257  0.42390717
 -0.03882451 -0.1885931  -0.42923521 -0.23275388  0.25167815  0.23645163
 -0.08557938 -0.4239232 ]
[0.28250342 0.45662651 0.22633228 0.30394271 0.0153061  0.10791063
 0.11257571 0.27519945 0.36548304 0.22713978 0.33924257 0.42390717
 0.03882451 0.1885931  0.42923521 0.23275388 0.25167815 0.23645163
 0.08557938 0.4239232 ]


## Tableaux 2D (et nD)
* meshgrid, indices, fromfunction
* methodes/numpy functions
* linear algebra, matrices

In [89]:
a = np.array([[1, 2, 4], [1, 5, 6], [2, 13, 7], [2, 0, 7]])
print(a)
a.shape

[[ 1  2  4]
 [ 1  5  6]
 [ 2 13  7]
 [ 2  0  7]]


(4, 3)

In [92]:
a[0:2, 1:]

array([[2, 4],
       [5, 6]])

In [94]:
a[:, 1]

array([ 2,  5, 13,  0])

In [96]:
np.zeros((4, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [98]:
np.random.rand(4, 3)

array([[0.59654795, 0.43935545, 0.68100065],
       [0.33905381, 0.94963542, 0.60802597],
       [0.8637304 , 0.90510887, 0.74126709],
       [0.9127427 , 0.67825961, 0.76052289]])

In [103]:
x = np.random.normal(size=(4, 3))
print(x)

[[-0.08021635  1.37551516 -0.64918992]
 [ 0.1836514  -0.95725155 -0.21368976]
 [-0.46868065 -0.27442198 -0.63140443]
 [ 0.30383456  1.06012571 -0.19392573]]


In [104]:
2*x + np.sin(x)

array([[-0.24056305,  3.73202347, -1.90292115],
       [ 0.54992358, -2.7321153 , -0.6394467 ],
       [-1.38907091, -0.81983455, -1.85308785],
       [ 0.90685043,  2.99266836, -0.58056398]])

In [106]:
x.min(axis=1)

array([-0.64918992, -0.95725155, -0.63140443, -0.19392573])

In [107]:
x = np.linspace(0, 1, 5)
y = np.linspace(10, 20, 4)
print(x)
print(y)

[0.   0.25 0.5  0.75 1.  ]
[10.         13.33333333 16.66666667 20.        ]


In [108]:
meshgrid(x, y)

[array([[0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ]]),
 array([[10.        , 10.        , 10.        , 10.        , 10.        ],
        [13.33333333, 13.33333333, 13.33333333, 13.33333333, 13.33333333],
        [16.66666667, 16.66666667, 16.66666667, 16.66666667, 16.66666667],
        [20.        , 20.        , 20.        , 20.        , 20.        ]])]

## Matrix


In [114]:

a = np.random.rand(4, 3)
a*a # not the matrix product. product of each item

array([[0.22724476, 0.0097205 , 0.22464135],
       [0.10481842, 0.284264  , 0.3380781 ],
       [0.65936284, 0.17733599, 0.45179885],
       [0.88789976, 0.08387878, 0.20471588]])

In [111]:
a = np.random.rand(4, 3)
b = np.random.rand(3, 4)

np.dot(a, b)

array([[0.66892901, 0.6059491 , 0.7175283 , 0.36405083],
       [1.17910382, 0.64278252, 1.11221531, 0.52566966],
       [0.25385315, 0.25478038, 0.28433385, 0.16017147],
       [0.80389113, 0.43259556, 0.72466159, 0.20305528]])

In [113]:
a@b # @ is the mat mul

array([[0.66892901, 0.6059491 , 0.7175283 , 0.36405083],
       [1.17910382, 0.64278252, 1.11221531, 0.52566966],
       [0.25385315, 0.25478038, 0.28433385, 0.16017147],
       [0.80389113, 0.43259556, 0.72466159, 0.20305528]])

In [117]:
a = np.random.rand(4, 3)
print(a)
b = a.flatten()
print(b)
c = b.reshape((3, 4))
print(c)

[[0.18386579 0.81106307 0.67171155]
 [0.33376569 0.25455575 0.48557205]
 [0.51590169 0.14151379 0.46122121]
 [0.45869678 0.79142243 0.77481542]]
[0.18386579 0.81106307 0.67171155 0.33376569 0.25455575 0.48557205
 0.51590169 0.14151379 0.46122121 0.45869678 0.79142243 0.77481542]
[[0.18386579 0.81106307 0.67171155 0.33376569]
 [0.25455575 0.48557205 0.51590169 0.14151379]
 [0.46122121 0.45869678 0.79142243 0.77481542]]


In [118]:
a = np.random.rand(4)
b = np.random.rand(4)
np.sum(a*b)

0.9616861901767916

# Broadcast



In [123]:
a = np.zeros((10, 3))
a[:,0] = np.arange(10)
print(a)

[[0. 0. 0.]
 [1. 0. 0.]
 [2. 0. 0.]
 [3. 0. 0.]
 [4. 0. 0.]
 [5. 0. 0.]
 [6. 0. 0.]
 [7. 0. 0.]
 [8. 0. 0.]
 [9. 0. 0.]]


In [126]:
b = np.array([1])
print(b.shape)
a[:,1] = b
a

(1,)


array([[0., 1., 0.],
       [1., 1., 0.],
       [2., 1., 0.],
       [3., 1., 0.],
       [4., 1., 0.],
       [5., 1., 0.],
       [6., 1., 0.],
       [7., 1., 0.],
       [8., 1., 0.],
       [9., 1., 0.]])

In [128]:
a = np.zeros((10, 3))
a[:,:] = 2
a

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [131]:
b = np.array([[1, 3, 5]])
print(b)
print(b.shape)
a[:,:] = b
a

[[1 3 5]]
(1, 3)


array([[1., 3., 5.],
       [1., 3., 5.],
       [1., 3., 5.],
       [1., 3., 5.],
       [1., 3., 5.],
       [1., 3., 5.],
       [1., 3., 5.],
       [1., 3., 5.],
       [1., 3., 5.],
       [1., 3., 5.]])

In [132]:
a = np.random.rand(10, 3)
print(a)
print(b)


[[0.1857228  0.8657378  0.88639247]
 [0.61473724 0.51612081 0.58622219]
 [0.85545688 0.94000242 0.81845709]
 [0.88842211 0.13207702 0.54177449]
 [0.01157231 0.79925325 0.19085829]
 [0.59656501 0.22916911 0.03490096]
 [0.02610431 0.75774067 0.4661917 ]
 [0.66764196 0.33934076 0.55471736]
 [0.34523164 0.67076264 0.77540991]
 [0.88153058 0.46358648 0.56571332]]
[[1 3 5]]


In [133]:
a + b

array([[1.1857228 , 3.8657378 , 5.88639247],
       [1.61473724, 3.51612081, 5.58622219],
       [1.85545688, 3.94000242, 5.81845709],
       [1.88842211, 3.13207702, 5.54177449],
       [1.01157231, 3.79925325, 5.19085829],
       [1.59656501, 3.22916911, 5.03490096],
       [1.02610431, 3.75774067, 5.4661917 ],
       [1.66764196, 3.33934076, 5.55471736],
       [1.34523164, 3.67076264, 5.77540991],
       [1.88153058, 3.46358648, 5.56571332]])

In [134]:
np.random.rand(10, 5) + b

ValueError: operands could not be broadcast together with shapes (10,5) (1,3) 

In [146]:
np.nan # Not a number

a = np.zeros(10)
a[2] = np.nan
a[~np.isnan(a)].min()

0.0

In [141]:
np.inf - np.inf

nan

### Array of booleans

In [150]:
a = np.array([True, False, True, True])
b = np.array([False, True, True, False])

# a and b
a&b
a|b
~a

array([False,  True, False, False])

## getitem et setitem
* indices
* slices
* tableaux booléens

## Saving/reading Numpy array
* ASCII
* Binary

In [152]:
a = np.random.rand(100, 3)
#a

In [155]:
np.savetxt('data.txt', a)

In [156]:
np.loadtxt('data_from_libre_office.csv')

array([[ 1.,  1.],
       [ 2.,  8.],
       [ 3., 65.],
       [ 4., 48.],
       [87., 34.],
       [64., 79.]])

In [158]:
a = np.random.rand(100000, 10)
np.savetxt('data.txt', a)

In [160]:
%timeit b = np.loadtxt('data.txt')

1.46 s ± 37.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [161]:
np.save('data.npy', a)

In [163]:
%timeit np.load('data.npy')

1.72 ms ± 95.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [164]:
np.loadtxt?

## Inside numpy array
* data, shape, strides
* Broadcast

In [165]:
a = np.random.rand(8, 3)
a

array([[0.70197568, 0.70748654, 0.43534272],
       [0.49678466, 0.57943017, 0.29520811],
       [0.78312205, 0.55505477, 0.94969496],
       [0.07338996, 0.230477  , 0.27237685],
       [0.97278602, 0.82574418, 0.03504461],
       [0.50985585, 0.31473913, 0.04706933],
       [0.77274695, 0.99936277, 0.5852463 ],
       [0.54224514, 0.65118871, 0.95375586]])

In [166]:
a.strides # a[i, j]

(24, 8)

In [170]:
b = a[:,2]
print(b.strides)

np.random.rand(4).strides

(24,)


(8,)

In [171]:
b[2] = 100
a

array([[7.01975678e-01, 7.07486539e-01, 4.35342721e-01],
       [4.96784659e-01, 5.79430170e-01, 2.95208108e-01],
       [7.83122047e-01, 5.55054767e-01, 1.00000000e+02],
       [7.33899592e-02, 2.30476999e-01, 2.72376855e-01],
       [9.72786017e-01, 8.25744177e-01, 3.50446090e-02],
       [5.09855854e-01, 3.14739130e-01, 4.70693337e-02],
       [7.72746946e-01, 9.99362770e-01, 5.85246299e-01],
       [5.42245141e-01, 6.51188709e-01, 9.53755858e-01]])